spring.application.name=auth-service
server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

security.jwt.secret=change-this-secret-key-to-a-long-256-bit-secret-value-123456
security.jwt.expiration-ms=3600000

management.endpoints.web.exposure.include=health,info
